name: iOS Build

on:
  push:
    branches: [ main1 ]
  pull_request:
    branches: [ main1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm i

    - name: Run prebuild script
      run: npm run prebuild

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
    - name: Install cli
      run: |
        npm install -g @ionic/cli@7.2.0
        npm install -g @capacitor/cli@7.2.0

    - name: Add iOS platform
      run: |
        npx cap add ios
    - name: Bump version & update native
      run: |
        npm install plist
        node ./scripts/bump-version.js

    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod install
        cd ../..

    - name: Setup keychain
      run: |
        security create-keychain -p "" ios-build.keychain
        security default-keychain -s ios-build.keychain
        security unlock-keychain -p "" ios-build.keychain
        security import <(echo "$IOS_CERT" | base64 --decode) -k ios-build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    - name: Build IPA
      run: |
        cd ios/App
        xcodebuild \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath $RUNNER_TEMP/App.xcarchive archive \
          DEVELOPMENT_TEAM=<your_team_id> \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER=<your_profile_name>

        xcodebuild -exportArchive \
          -archivePath $RUNNER_TEMP/App.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $RUNNER_TEMP/build

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-ios
        path: ios/App/build/Release-iphoneos/App.ipa 